loadstring(game:HttpGet("https://raw.githubusercontent.com/mame1123ccc/mametp/refs/heads/main/ghostrule.lua"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/mame1123ccc/mametp/refs/heads/main/local%20lava.lua"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/mame1123ccc/mametp/refs/heads/main/serverlava.lua"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/mame1123ccc/mametp/refs/heads/main/locallava2.lua"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/mame1123ccc/mametp/refs/heads/main/serverlava2.lua"))()
